name: Python application

on: [push, pull_request]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install -r requirements.txt || true

    - name: Run tests
      run: |
        python -m unittest discover -s . -p 'TestApp.py'
  dockerimage:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Log in to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: gravehg/github-homework-12-aseguramiento:latest
  
